//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasty
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard_type
    {
        public int CardID { get; set; }
        public string CardName { get; set; }
        public string StartsWith { get; set; }
        public decimal length { get; set; }
    }
}
