//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasty
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ItemId { get; set; }
        [Required(ErrorMessage = "Please enter Item Name")]
        public string ItemName { get; set; }
        [Required(ErrorMessage = "Please enter Quantity")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only Digits")]
        public Nullable<int> Quantity { get; set; }
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only Digits")]
        public string BasePrice { get; set; }
        //[Required(ErrorMessage = "Please upload Image")]
        public string img_src { get; set; }

        public System.Web.HttpPostedFileBase ImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
