//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasty
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Payment
    {
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        [Required(ErrorMessage = "Please enter the Card Number")]
        [StringLength(16, MinimumLength = 15, ErrorMessage = "Invalid Card Number")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only Digits")]
        [Display(Name = "Card Number")]
        public string CardNumber { get; set; }
        [Required(ErrorMessage = "Please enter the name on card")]
        [Display(Name = "Name On Card")]
        [RegularExpression(@"^[a-zA-Z]{5,20}$", ErrorMessage = "Invalid characters")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Only 5-20 characters allowed")]
        public string CardName { get; set; }
        [Required(ErrorMessage = "Please Enter CVV")]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Invalid CVV")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Only Digits")]
        [Display(Name = "CVV")]
        [DataType(DataType.Password)]
        public Nullable<int> Cvv { get; set; }
        [Display(Name = "Expiry Date")]
        [Required(ErrorMessage = "Please enter the expiry date")]
        [RegularExpression(@"(0[1-9]|10|11|12)/(201[6-9]|202[0-9]|2030|2031)$", ErrorMessage = "Invalid Expiry date")]
        public string ExpiryDate { get; set; }
        [NotMapped]
        public string cardType { get; set; }
        public virtual Order Order { get; set; }
    }
}
